---
- name: Setup Website on web group
  hosts: websrvgrp
  become: yes
  remote_user: devops
#  vars_prompt:
#    - name: "WEBURL"
#      prompt: "Enter the URL for web template from tooplate.com"
#    - name: "DIRNAME"
#      prompt: "Enter the Directory NAME in the template zip file."
  vars:
    WEBURL: https://www.tooplate.com/download/2112_brunch
    DIRNAME: 2112_brunch

  tasks:

#   - debug:
#       msg: "You have entered WEBURL {{WEBURL}}"         

#   - debug:
#       msg: "You have entered Directory NAME {{DIRNAME}}"
         
   - name: Install httpd
     yum: 
        name: "{{ item }}"
        state: present
     loop:
       - httpd
       - wget
       - unzip
       - git

   - name: Start and Enable HTTPD
     service:
        name: httpd
        state: started
        enabled: yes
  
   - name: Download Website from tooplate.com
     get_url:
        url: "{{WEBURL}}"
        dest: "/tmp/{{DIRNAME}}.zip"

   - name: Unzip website.zip
     unarchive:
       src: "/tmp/{{DIRNAME}}.zip"
       dest: /tmp/
       remote_src: yes
     register: unzip_task

   - name: Copy files from template directory to /var/www/html
     shell: "cp -r /tmp/{{DIRNAME}}/* /var/www/html/"
     when: unzip_task.changed
     notify: 
       - Restart HTTPD Service
  
  handlers:
   - name: Restart HTTPD Service
     service:
       name: httpd
       state: restarted

            
